# Add golint to golang image
# build image
# 1). cd current directory
# 2). run "docker build -t golang:custom ."

FROM golang:latest

# MAINTAINER 维护者信息
MAINTAINER chenguolin

# get golint
RUN go get github.com/golang/lint/golint

