CREATE TABLE `users` (
  `id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `uid` BIGINT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户uid',
  `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户名称',
  `phone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户电话',
  `create_time` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
   PRIMARY KEY (`id`),
   UNIQUE KEY `uk_uid` (`uid`) USING BTREE COMMENT '唯一索引'
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
